### ISSUE TITLE
Any plans to publish in npm?

### ISSUE THREAD

**Issue by princed** [xdissent/karma-chai#2]

**Comment by xdissent** [comment]
Yes, I was waiting for the new Karma plugin api to stabilize a bit.

**Comment by princed** [comment]
Hey again, I've also published [except.js adapter](https://github.com/princed/karma-expect) for testing in olds IEs.
Maybe you'll find it useful.

**Comment by princed** [comment]
Karma 0.10 is out now, could you please publish karma-chai?
I'd like to use it as peer dependency for [karma-chai-plugins](https://github.com/princed/karma-chai-plugins).

**Comment by xdissent** [comment]
Hey thanks for your patience! Finally pushed it out today and updated my other plugins.
