### ISSUE TITLE
Need to update rev and new tag

### ISSUE THREAD

**Issue by jyonker** [xdissent/karma-chai#4]
Hello,

   In October you bumped the version of chai dependency to 1.8.1 but neglected to bump the version and tag of the plugin, so we are not getting the latest version without a delete and re-install.

   Please create tag 0.0.2.  

thanks

**Comment by xdissent** [comment]
Ah, thank you - I had planned to release but got sidetracked.

**Comment by alexgorbatchev** [comment]
out of date, closing
