### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by alexgorbatchev** [xdissent/karma-chai#8]
Hey Greg,

I feel that this fork https://github.com/JohanObrink/karma-chai-sinon now supersedes `karma-chai`... perhaps it's time to deprecate? Or does it still have a place since it only brings `chai` letting users bring a stubbing framework other than `sinon`? 

Thoughts?

**Comment by willmruzek** [comment]
Although Sinon and Chai are a great pair, I think it makes sense to keep `karma-chai` as a separate module. It would nice, though, is Chai was listed as a peer dependency like in `karma-mocha` See https://github.com/karma-runner/karma-mocha/blob/master/package.json

This way the Chai version wouldn't need to be bumped everytime.

**Comment by alexgorbatchev** [comment]
moved `chai` to `peerDependencies` and republished.

**Comment by xdissent** [comment]
:clap: :clap:
